### ISSUE TITLE
GLOG_INCLUDE_DIRS in FindGlog.cmake

### ISSUE THREAD

**Issue by omersahintas** [KIT-MRT/mrt_cmake_modules#22]
Cmake fails to bind glog with:
`mrt_cmake_modules/cmake/Modules/FindGlog.cmake:366 (list): 
list sub-command REMOVE_ITEM requires list to be present.`

If lines
`list(REMOVE_ITEM GLOG_INCLUDE_DIRS "/usr/include")`
`list(REMOVE_ITEM GLOG_INCLUDE_DIRS "/usr/local/include")`
are deleted, it builds without any problem.

The `list()` commands are not present in other find scripts such as [Ceres-solver](https://github.com/ceres-solver/ceres-solver/blob/master/cmake/FindGlog.cmake#L376). What is the reason behind to add these lines?

**Comment by poggenhans** [comment]
What is your cmake version? I don't get this error with any cmake version since 3.14.

These lines are there because in some versions of glog `GLOG_INCLUDE_DIRS` contains `/usr/include`. This must not happen because it messes up the order in which include directories are searched by the compiler (`/usr/include` should always be searched last).

**Comment by omersahintas** [comment]
Okay, apparently CMake 3.10 cannot get along with empty lists :+1:
