### ISSUE TITLE
ROS Build Farm Release

### ISSUE THREAD

**Issue by JWhitleyWork** [KIT-MRT/mrt_cmake_modules#9]
I've asked this about `lanelet2` (see https://github.com/fzi-forschungszentrum-informatik/Lanelet2/issues/53) but this package is a prerequisite. I would be happy to help release this package. `lanelet2` is a requirement for the Autoware.ai (and will likely be for Autoware.Auto as well) and is taking a huge portion of our CI build time to build. Having binary packages distributed from the build farm would be a major boon.

**Comment by JWhitleyAStuff** [comment]
Any thoughts from the maintainers on this?

**Comment by poggenhans** [comment]
Sorry for taking so long to reply. We are actively working on this, but it is/has been taking us some time because this package first needed a lot of changes in order to be to be in a releasable state. It mixed a lot of internal stuff (like #7)  with actually useful things.

This will most likely be finished this week. After that we can start working towards the ROS release.

**Comment by JWhitleyAStuff** [comment]
Thanks, @poggenhans ! If you guys need any help releasing to the build farm, feel free to contact me at jwhitley@autonomoustuff.com (until Feb 14th - I'll be at a new job the following week).

**Comment by poggenhans** [comment]
See https://github.com/ros/rosdistro/pull/23863

**Comment by JWhitleyWork** [comment]
@poggenhans Thank you! The `autoware.ai` community thanks you!
